apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-server-data
  labels:
    app: factorio-server
spec:
  metadata:
    labels:
      app: factorio-server
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "15Gi"