apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-server-data
  namespace: factorio-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-server-data
  namespace: factorio-server
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/factorio"
